definitions:
  api.EncryptRequest:
    properties:
      pemKey:
        description: Ключ как строка
        type: string
      text:
        type: string
    required:
    - pemKey
    - text
    type: object
  api.Keys:
    properties:
      private:
        type: string
      public:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/cypher/elliptic/decrypt:
    post:
      consumes:
      - application/json
      description: Decrypt the provided text using the given public key
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/api.EncryptRequest'
      produces:
      - text/plain
      responses:
        "200":
          description: Decrypted data
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Decrypt data
      tags:
      - encryption
  /api/cypher/elliptic/encrypt:
    post:
      consumes:
      - application/json
      description: Encrypt the provided text using the given public key
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/api.EncryptRequest'
      produces:
      - text/plain
      responses:
        "200":
          description: Encrypted data
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Encrypt data
      tags:
      - encryption
  /api/cypher/elliptic/keys:
    get:
      consumes:
      - application/json
      description: Generate a public key using the elliptic curve algorithm
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Keys'
      summary: Generate a public key
      tags:
      - keys
swagger: "2.0"
